### ISSUE TITLE
Send notification meet 500 error: Expected BEGIN_OBJECT but was STRING

### ISSUE THREAD

**Issue by itayloryan** [TwilioDevEd/sdk-starter-java#27]
Server: sdk-stater-java
Client: video-quick-start-android/exampleVideoInvite

```
Notification notification = new Notification(
                "Join " + mIdentity + " in room " + roomName,
                mIdentity + " has invited you to join video room " + roomName,
                inviteJsonString,
                NOTIFY_TAGS);
        TwilioSDKStarterAPI.notify(notification).enqueue(new retrofit2.Callback<Void>() {
            @Override
            public void onResponse(retrofit2.Call<Void> call, retrofit2.Response<Void> response) {
                if (!response.isSuccessful()) {
                    String message = "Sending notification failed: " + response.code() + " " + response.message();
                    Log.e(TAG, message);
                    videoStatusTextView.setText(message);
                }
            }

            @Override
            public void onFailure(retrofit2.Call<Void> call, Throwable t) {
                String message = "Sending notification failed: " + t.getMessage();
                Log.e(TAG, message);
                videoStatusTextView.setText(message);
            }
        });
```

```
public class Notification {
    @SerializedName("Title")
    public final String title;
    @SerializedName("Body")
    public final String body;
    @SerializedName("Data")
    public final String data;
    @SerializedName("Tag")
    public final List<String> tag;

    public Notification(String title, String body, String data, List<String> tag) {
        this.title = title;
        this.body = body;
        this.data = data;
        this.tag = tag;
    }

}
```

**Error:**
```
36368 [qtp445395875-13] ERROR com.twilio.ServerApp - Exception creating notification: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:868)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.twilio.ServerApp.lambda$main$7(ServerApp.java:196)
	at spark.RouteImpl$1.handle(RouteImpl.java:61)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:139)
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:70)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	... 22 more
```

**Comment by jishindev** [comment]
Same server and client and same issue here. The data object is sent as a string and not an object.

> Request - POST /send-notification

```json
{
    "body": "TannerDitch32 has invited you to join video room test",
    "data": "{\"fromIdentity\":\"TannerDitch32\",\"roomName\":\"test\"}",
    "tag": [
        "video"
    ],
    "title": "Join TannerDitch32 in room test"
} 
```


> Response - 500 Server Error

```json
{
"message":"Failed to create notification: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING",
"error":"java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING"
}
```

**Comment by jefflinwood** [comment]
Thanks for identifying this as an issue - the workaround in the above would work for fixing the problem, but I am going to work on getting a fix in on the Example Video app:

https://github.com/twilio/video-quickstart-android/blob/master/exampleVideoInvite/src/main/java/com/twilio/video/examples/videoinvite/VideoInviteActivity.java#L504

**Comment by itayloryan** [comment]
@jishindev @jefflinwood  Thank you guys :100:

**Comment by jefflinwood** [comment]
Hi,

See - https://github.com/twilio/video-quickstart-android/pull/373
