### ISSUE TITLE
.env file not working

### ISSUE THREAD

**Issue by soeviturek** [TwilioDevEd/sdk-starter-java#59]
I am getting this error when running the app, it seem like it failed the authentication, however all my api keys, service keys and account sid are correct and it works fine in the nodejs one.
Exception in thread "main" com.twilio.exception.ApiException: Authenticate
        at com.twilio.rest.sync.v1.ServiceFetcher.fetch(ServiceFetcher.java:56)
        at com.twilio.rest.sync.v1.ServiceFetcher.fetch(ServiceFetcher.java:20)
        at com.twilio.base.Fetcher.fetch(Fetcher.java:40)
        at com.twilio.ServerApp.provisionSyncDefaultService(ServerApp.java:319)
        at com.twilio.ServerApp.main(ServerApp.java:93)
Am I doing something wrong?

**Comment by soeviturek** [comment]
Just realised that this issue is caused by difference in region between service and api. Recreating an api with the same region as the service would solve this.
